### ISSUE TITLE
Dependencies & DependencyLink

### ISSUE THREAD

**Issue by tsuna** [openzipkin/zipkin-go-opentracing#102]
Hi there,
any reason why the generated Go code for `zipkinDependencies.thrift` wasn't included under `thrift/gen-go/zipkincore`?

**Comment by basvanbeek** [comment]
Because it is not used by the library itself and don't want the responsibility of having to keep it in sync/updated if not valuable to this repo.

If you have a need for this code get it from the official source: https://github.com/openzipkin/zipkin-api/tree/master/thrift
