### ISSUE TITLE
improved readme

### ISSUE THREAD

**Issue by basvanbeek** [openzipkin/zipkin-go-opentracing#12]
project needs improved readme with examples of zipkin tracer specific settings like `ClientServerSameSpan`

**Comment by adriancole** [comment]
would also be nice to make a demo like below to help users acclimate in a straightforward way https://github.com/openzipkin/zipkin-finagle-example

**Comment by adriancole** [comment]
plus @CodingFabian on this https://twitter.com/CodingFabian/status/773058220269133824

**Comment by basvanbeek** [comment]
I will pick this up in a week or two. We're about to launch a new platform so very much tied up at the moment. I like the idea of adding a real example. I will do this inside the repository itself so it is part of CI testing and will force us to keep it updated.

**Comment by basvanbeek** [comment]
Just made a quick and dirty example with two services and a client and added a PR for it.

It might need some additional work to clean up but wanted people to at least have something to look at for now.

**Comment by basvanbeek** [comment]
With the examples and a little more verbose readme added, i'm closing this issue
