### ISSUE TITLE
Basic Go API using Zipkin

### ISSUE THREAD

**Issue by antlsung** [openzipkin/zipkin-go-opentracing#15]
Hi, so I'm trying to implement a basic GO api using the go-opentracing, but there are like no examples that I have been able to find. Do you know of any good examples to base my API off of? I'm trying to use the scribe collector and its compiling fine, but none of my spans/traces are being sent to the Zipkin collector. I've included my code in case anybody might be able to debug any glaring mistakes. Appreciate any help!

c, err := zipkintracer.NewScribeCollector("dockerhost:9042",timeout,zipkintracer.ScribeBatchSize(1),zipkintracer.ScribeBatchInterval(batchInterval))
	if err != nil {
		log.Fatal(err)
	}
	span := zipkincore.NewSpan()
	span.ID = int64(999)
	span.TraceID = int64(999)
	span.Name = "test"

	annotate1 := zipkincore.NewAnnotation()
	sr := zipkincore.NewEndpoint()
	sr.Ipv4 = (127 << 24) | 1
	sr.Port = 8181
	annotate1.Host = sr
	annotate1.Timestamp = time.Now().UnixNano() / 1e3
	annotate1.Value = "test"

	annotations := []*zipkincore.Annotation{
		annotate1,
	}
	binAnnotations := []*zipkincore.BinaryAnnotation{
		binAnnotate,
	}
	var dur = int64(100)
	span.Duration = &dur
	span.Annotations = annotations
	span.BinaryAnnotations = binAnnotations

	c.Collect(span)

**Comment by basvanbeek** [comment]
This tracer is meant to be used with opentracing-go as the managing API. So for examples on usage check: https://github.com/opentracing/opentracing-go

The only thing you'd do in this package is create the Collector and then create the Tracer:

```go
	collector, err := zipkin.NewKafkaCollector([]string{"10.0.0.139:9092","10.0.0.140:9092"})
	if err != nil {
		...
	}
	tracer, err = zipkin.NewTracer(
		zipkin.NewRecorder(collector, false, "10.0.0.15", "MyService"),
		zipkin.ClientServerSameSpan(true), // for Zipkin V1 RPC span style
	)
	if err != nil {
		...
	}
	// make sure we set our tracer as the default tracer
	opentracing.InitGlobalTracer(tracer)
	...
	... from here on use opentracing API calls...
```

For more info check this blog post: 

https://medium.com/opentracing/distributed-tracing-in-10-minutes-51b378ee40f1

**Comment by antlsung** [comment]
Thanks you!
