### ISSUE TITLE
Java/Go Zipkin API's

### ISSUE THREAD

**Issue by antlsung** [openzipkin/zipkin-go-opentracing#16]
Hi,

So I am trying to build a multi-language tracing system that works on Java and Go. The Java API's are working and propagating trace data through HTTP headers, but the GO api is unable to get the span context from the parent Java api. The GO api is able to send basic spans to Zipkin (without propagated traceId and parentId) and I can get the HTTP header being sent to the GO API, but I can't seem to manually set the zipkintracer.Span fields for traceId/parentSpanId. Any clues?

**Comment by basvanbeek** [comment]
can you try to create the tracer with the following option and see if it works then:
```
tracer, err := NewTracer(recorder, ClientServerSameSpan(true))
```

This will set the tracer to Zipkin span per RPC mode...

**Comment by antlsung** [comment]
The tracer is working right now when I just use tracer.StartSpan(methodName) but not when I use 	tracer.StartSpan("get_loan",opentracing.ChildOf(someContext)).

**Comment by antlsung** [comment]
Really, I'm just looking for a way to send a zipkincore.Span. Right now, only the opentracing.Span is working with the zipkintracer and that doesn't have any of the traceId, spanId, parentId fields.

**Comment by basvanbeek** [comment]
Are you using the Extract logic to get the headers into the context? They don't magically appear there...

I suggest taking a look at the Go kit package:
- https://github.com/go-kit/kit/tree/master/tracing/opentracing

more specifically for HTTP B3 propagation:
- https://github.com/go-kit/kit/blob/master/tracing/opentracing/http.go

**Comment by antlsung** [comment]
Gotcha, I guess I don't fully understand how to extract and inject the headers properly. My JAVA api is sending the trace propagation data via the HTTP headers and I'm extracing it using:
`context,err:=tracer.Extract(opentracing.TextMap,opentracing.HTTPHeaderTextMapCarrier(r.Header))`

Then I want to use the context to make my new span so it will link up with the current trace and be the child of the previous service. So I used this: 
`tracer.Inject(context,opentracing.TextMap,opentracing.HTTPHeaderTextMapCarrier(r.Header))`
`span:= tracer.StartSpan("get_loan")`
`span.Finish()`
Should this theoretically work?

**Comment by basvanbeek** [comment]
You are correct on the `tracer.Extract` part. This will try to retrieve the B3 headers from `r.Header` and put them into `context`

Tracer.Inject you will need to call when you need the span you've created in Go land to be the parent span to be propagated to a downstream service. So you use this only when doing an RPC call from Go to another service.

If you want to create a span in your local service when handling an incoming RPC call you'd typically use the tracer.Extract() stuff in your middleware to receive the wire context. From there you can simple create your server side span like this:

```go
wireContext, _ := tracer.Extract(opentracing.TextMap, opentracing.HTTPHeaderTextMapCarrier(r.Header))
span := tracer.StartSpan("get_loan", ext.RPCServerOption(wireContext))
```

either do stuff with that span immediately or push the newly created server side span into context like this and pick it up in your service method from context:
```go
context := opentracing.ContextWithSpan(ctx, span)
```

do not forget in the end to call span.Finish() on the span or it won't be collected

**Comment by antlsung** [comment]
So Zipkin is now receiving the spans, but it is not changing the traceId/spanId to my header values. They are still the randomly generated span ID values.
`context,err:=tracer.Extract(opentracing.TextMap,opentracing.HTTPHeaderTextMapCarrier(r.Header))`
	`span:= tracer.StartSpan("get_loan",ext.RPCServerOption(context))`
	`span.Finish()`

These are my header values:
X-B3-TraceId =  1
X-B3-SpanId =  2
X-B3-ParentSpanId =  1

**Comment by antlsung** [comment]
Figured it out, I haven't been giving it all the header values needed. It needs the X-B3-Sampled to be true in order for it to use the context values. Thanks for all the help!

**Comment by ashutoshinvincible** [comment]
collector, errCol := zipkin.NewHTTPCollector(zipkinHTTPEndpoint)
          if errCol != nil {
                fmt.Printf("unable to create Zipkin HTTP collector: %+v", errCol)
                os.Exit(-1)
          }
          recorder := zipkin.NewRecorder(collector, true, hostPort, serviceName)
          tracer, errCol := zipkin.NewTracer(
                recorder,
                zipkin.ClientServerSameSpan(sameSpan),
                zipkin.TraceID128Bit(traceID128Bit),
          )
          if errCol != nil {
                fmt.Printf("unable to create Zipkin tracer: %+v", errCol)
                os.Exit(-1)
          }
req,_ := http.NewRequest("GET", "URL", nil)
         req.Header.Set("X-B3-TraceId", "")
         req.Header.Set("X-B3-SpanId", "")
         req.Header.Set("X-B3-ParentSpanId","")
         req.Header.Set("X-B3-Sampled","true")
extContext,_ :=tracer.Extract(opentracing.TextMap,opentracing.HTTPHeadersCarrier(req.Header))

          // explicitly set our tracer to be the default tracer.
          opentracing.InitGlobalTracer(tracer)
          span := opentracing.StartSpan("Start Span",ext.RPCServerOption(extContext))
          span.LogEvent("Start Pipeline") 


Used this code but trace is not getting generated .

**Comment by ashutoshinvincible** [comment]
@basvanbeek @antlsung

**Comment by ashutoshinvincible** [comment]
@adriancole

**Comment by basvanbeek** [comment]
@ashutoshinvincible  easier would be creating an explicit SpanContext and feeding this to StartSpan:

```go
    manualSpanContext := zipkin.SpanContext{
        SpanID: 1,
        TraceID: types.TraceID{
            High: 0,
            Low:  1,
        },
        Sampled: true,
    }
    span := tracer.StartSpan("MyOperationName", ext.RPCServerOption(manualSpanContext))
    defer span.Finish()
```

don't forget the sampled = true or it will be discarded at collection time...

**Comment by ashutoshinvincible** [comment]
traceIdObj,_ := types.TraceIDFromHex("22b1e85d9b0b1b92")
	   strSpanId,_ := strconv.ParseUint("2f2b74a2dff15ef4", 16, 64)
	   manualSpanContext := zipkin.SpanContext{
			ParentSpanID: &strSpanId,
			TraceID: traceIdObj,
			Sampled: true,
		}
	 opentracing.InitGlobalTracer(tracer)
	 span := opentracing.StartSpan("Start Span",ext.RPCServerOption(manualSpanContext)) 

	traceId	22b1e85d9b0b1b92
	spanId	0000000000000000
	parentId	2f2b74a2dff15ef4

Child span is getting created with following details but SpanId is not getting auto generated in the child span and is showing up as spanId 0000000000000000 in zipkin UI

**Comment by basvanbeek** [comment]
That's correct because you did not set the span id in manualSpanContext and gave the span id you picked up somewhere to ParentSpanID.
