### ISSUE TITLE
Update the Apache thrift package ref

### ISSUE THREAD

**Issue by Dynom** [openzipkin/zipkin-go-opentracing#20]
At the moment git.apache.org/thrift.git/lib/go/thrift seems down, while it's mirror https://github.com/apache/thrift is up. I'm not sure if the mirror is legitimate, but at least it's up.

Currently I have no way of solving a Go dependency situation with this reference in place.

**Comment by bensigelman** [comment]
:+1: in that git.apache.org is often incredibly slow even when it *is* working :)

(And given that github.com/apache/thrift is part of the github.com/apache org, it must be at least mostly-legitimate.)

**Comment by basvanbeek** [comment]
Update has been made. Thanks
