### ISSUE TITLE
zipkin http header keys in canonical format

### ISSUE THREAD

**Issue by chihhsiw** [openzipkin/zipkin-go-opentracing#23]
Hi,
   we are experimenting go-kit micro service with openzipkin/zipkin-go-opentracing. One thing I found is that the HTTP header keys like  "X-B3-TraceId, X-B3-SpanId, X-B3-ParentSpanId" according to  http://zipkin.io/pages/instrumenting.html   BECOMES "X-B3-Traceid, X-B3-Spanid, X-B3-Parentspanid" when the http header is sent from go-kit micro service using zipkin-go-opentracing. 
   While this is fine for tracing between go-kit micro services because the Extract() method of zipkin-go-opentracing/propagation_ot.go resolves the case difference. 
   However, when the go-kit micro service sends requests with trace to other services  implemented in Java or C/C++, the canonical format could create mismatch. 
   I believe whoever implemented the Extract() method of zipkin-go-opentracing/propagation_ot.go understands the issue I'm talking about.
   Any idea on how to resolve this discrepancy between zipkin instruments implemented by different languages?

thanks

**Comment by basvanbeek** [comment]
Problem is that server side instrumentation really should treat HTTP headers as case insensitive per RFC. Most browsers capitalize words (words separated by -) So `X-B3-TraceId` would become `X-B3-Traceid`

In Go this is done by net/http automatically see:
https://golang.org/src/net/http/header.go?s=711:749#L166

So unfortunately there is not much we can do here, you can however file a report with the other tracing libraries you are using to make sure they treat the headers in a case insensitive matter as they should.

**Comment by adriancole** [comment]
Agreed. It is a bug to read http header names case sensitively.

**Comment by basvanbeek** [comment]
I'm closing this issue. It needs to be resolved in the other libraries / implementations.
