### ISSUE TITLE
NewRecorder() should check that makeEndpoint() does not return nil

### ISSUE THREAD

**Issue by drscre** [openzipkin/zipkin-go-opentracing#32]
`NewRecorder()` calls `makeEndpoint() ` without checking whether it returns `nil`: [zipkin-recorder.go#L34](https://github.com/openzipkin/zipkin-go-opentracing/blob/v0.1.0/zipkin-recorder.go#L34)

Absence of `nil` check leads to hard to understand nil pointer panics (which can happen because of malformed hostPort, for intsance)

In my case i used malformed `hostPort` without host ":8080" and recieived nil pointer panic from [zipkin-recorder.go#L112](https://github.com/openzipkin/zipkin-go-opentracing/blob/v0.1.0/zipkin-recorder.go#L112), which left me scrathing my head for a while

**Comment by basvanbeek** [comment]
Even better would be for makeEndpoint() to always return a proper `zipkincore.Endpoint` with sensible defaults. Created a PR for this and about to merge.
