### ISSUE TITLE
field.Key undefined

### ISSUE THREAD

**Issue by alighm** [openzipkin/zipkin-go-opentracing#38]
When using _zipkin.NewTracer(zipkin.NewRecorder(collector, false, hostPort, svcName))_
Inside the log-materializers.go, on the following functions:

```
// MaterializeWithLogFmt converts log Fields into LogFmt string
func MaterializeWithLogFmt(logFields []log.Field) ([]byte, error) {
	var (
		buffer  = bytes.NewBuffer(nil)
		encoder = logfmt.NewEncoder(buffer)
	)
	for _, field := range logFields {
		if err := encoder.EncodeKeyval(field.Key(), field.Value()); err != nil {
			encoder.EncodeKeyval(field.Key(), err.Error())
		}
	}
	return buffer.Bytes(), nil
}
```

```
// StrictZipkinMaterializer will only record a log.Field of type "event".
func StrictZipkinMaterializer(logFields []log.Field) ([]byte, error) {
	for _, field := range logFields {
		if field.Key() == "event" {
			return []byte(fmt.Sprintf("%+v", field.Value())), nil
		}
	}
	return nil, errEventLogNotFound
}
```
I am getting the following error:
`
field.Key undefined (type "vendor/github.com/opentracing/opentracing-go/log".Field has no field or method Key, but does have "vendor/github.com/opentracing/opentracing-go/log".key)
`

This makes sense because as I look at the **[]log.Field**, I see that the Field struct does not have a method called Key() which is exposing the key...

**Comment by basvanbeek** [comment]
please update your vendored opentracing-go package as field.Key() has been available for the last 3 months. See:

https://github.com/opentracing/opentracing-go/blob/master/log/field.go#L206

**Comment by alighm** [comment]
ok cool, I will go ahead and try this out first thing tomorrow morning and let you know the result! Appreciate it!

**Comment by basvanbeek** [comment]
@alighm did you get a chance to test?

**Comment by basvanbeek** [comment]
I'm going to close this. @alighm if you still experience issues feel free to open a new issue report.
