### ISSUE TITLE
`collector-http/Collect` can block application

### ISSUE THREAD

**Issue by eyal-stratoscale** [openzipkin/zipkin-go-opentracing#39]
Hi,

In the `collector-http.go`:
When zipkin is down or slow, the blocking `send` function can take up to `c.client.Timeout` seconds. in this period, the `Collect` function can block the application, because the select in the `loop` function does not extract spans from the `spanc`.

I think that running the code inside the collect function in a go routine might solve this problem.

Cheers,
Eyal

**Comment by basvanbeek** [comment]
It would mask the problem, not solve it. I will give it some thought.

Items to think about:
- parallel HTTP sends (not having serialized requests stall everything). this helps to increase throughput and lower reception latency if there are multiple collectors behind the endpoint.
- set-able HTTP connect/send/read timeouts
- high water thresholds (and what to do if we reach them; drop vs stall)
- set-able span buffer size to increase ability to spread spikes

**Comment by adriancole** [comment]
in the java reporter, we have a single looper thread that empties a bucket full of spans based on some configuration. in finagle, I think they are "mostly" async except there is some possibility of blocking. In general, it is nice not only from a blocking POV, but also protecting from any other types of failure unrelated to the caller.

**Comment by eyal-stratoscale** [comment]
@basvanbeek , Thanks for the answer. Points 2 and 4 are already there, and do not solve the issue, points 1 and 4 won't solve the problem.

I think, and as I understood @adriancole agrees, that in any case, no matter what, you should not block the application. Tracing is important, but should not interfere with the application flow.

The async loop is already implemented, but the `Collect` method might be blocking, which can lead to application blocking (as I've experienced).

Cheers

**Comment by basvanbeek** [comment]
I understand but simply running the Collect function implementation inside a go routine as you suggest will get you in other trouble (when the spanc channel buffer is full for a prolonged period and you continue to have many span Collect() invocations, the amount of goroutines being created and not flushed will have catastrophic consequences too. 

The real solution needs to be a deterministic well defined dropping of spans if we have egress bottlenecks above consumer set-able thresholds / high water marks.

I do not want to add a quick hack without first looking more holistically at how to solve these typical transport bottlenecks in a consistent manner across all our collector implementations.

In the mean time you're very welcome to send ideas and even better PRs / POCs.

**Comment by eyal-stratoscale** [comment]
I see your point, what do you say about running the `send` function in a go routine?

**Comment by bensigelman** [comment]
@basvanbeek 

> I do not want to add a quick hack without first looking more holistically at how to solve these typical transport bottlenecks in a consistent manner across all our collector implementations.

Couldn't agree more with ^^^. Take it or leave it, but LightStep has gone with a user-configurable flush interval (in seconds) and a user-configurable cap/max on the number of Spans that may be buffered for each flush. Any spans beyond that max are dropped (and tracked via a counter). YMMV.

**Comment by adriancole** [comment]
one suggestion would be to split this into two issues

For example, flush interval, max spans etc are very well explored, exist in
many tracers and address local overload (or what to do on backlog). These
settings are not transport specific with regards to errors or things that
could cause lots of blocking.

The second issue would be about error cases, for example, survivability on
transport-specific failure modes (while we like to think about failures
generically, there are certain patterns that exist in kafka, but not http),
backoff or fallback strategies.

In either case, there's a common thread (no pun intended), but I think they
are separate concerns or at least have different test case impact. For
example, simple backlog or slow ingest can be unit tested without
integration. Common Kafka failure modes require at least micro-integration
testing.

**Comment by posener** [comment]
@adriancole I agree, the fix I send does not deal with exploding backlog when zipkin is not responding.
