### ISSUE TITLE
_thrift directory ignored by gvt

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [openzipkin/zipkin-go-opentracing#42]
I tried to install `zipkin-go-opentracing` with [gvt](https://github.com/FiloSottile/gvt), and was surprised to find the `_thrift` directory missing from the checkout.

After some searching, I found that gvt [has some logic to ignore directories beginning with `_`](https://github.com/FiloSottile/gvt/blob/7ea07128fd266d5012be99c952746e74ec719851/fileutils/fileutils.go#L59). They justify this by linking to [golang's description of package lists](https://golang.org/cmd/go/#hdr-Description_of_package_lists) which states:

> Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata".

Perhaps it would be a good idea to remove the underscore from the `_thrift` directory in this package. If you think this is something that should be allowed by gvt please let me know, and I'd be happy to open a ticket with them.

Regards,
Igor

**Comment by basvanbeek** [comment]
As all the code under `_thrift` is generated I specifically prefixed with `_` so it would not be included in tests, coverage, linting, etc.

Seems GVT includes omitting behavior to extend to pulling in code too which is rather strange as one would expect the VC to not include items that should be ignored.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Thanks for explaining. I've opened a ticket with gvt as well, so I hope they choose to address it on their side. :)

**Comment by basvanbeek** [comment]
I'm going to close this as I don't see this as an error on my end. If GVT has a valid reason why to ignore this on the file checkout you can reopen and I will reassess.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Works for me, thanks! :)

**Comment by tomwilkie** [comment]
The new dep tool is also doing this: https://github.com/golang/dep/issues/298
