### ISSUE TITLE
Document hostPort parameter for NewRecorder()

### ISSUE THREAD

**Issue by F21** [openzipkin/zipkin-go-opentracing#45]
I am confused about what the `hostPort` parameter is used for when calling `NewRecorder()`. It would be nice if this can be better documented.

**Comment by basvanbeek** [comment]
Agreed. I will improve the documentation on parameters and settings.

`hostPort` sets the default "host:port" string for the service or client being instrumented. This host:port string will show up as the application's endpoint in the Zipkin traces it is part of.

**Comment by basvanbeek** [comment]
handled in PR #47
