### ISSUE TITLE
can not compile code with undefined: proto.GoGoProtoPackageIsVersion2 bug

### ISSUE THREAD

**Issue by modeyang** [openzipkin/zipkin-go-opentracing#46]
HI,  I  come across  some error issue when compile code with ```go get .```,  details is below
```
# github.com/openzipkin/zipkin-go-opentracing/wire
wire/wire.pb.go:31: undefined: proto.GoGoProtoPackageIsVersion2
wire/wire.pb.go:582: undefined: proto.RegisterFile
godep: exit status 2
```
also **proto.GoGoProtoPackageIsVersion2** can not be found in **github.com/golang/protobuf** project after pull all dependent codes. 
 any one who can help me fix this issue, thanks.

**Comment by basvanbeek** [comment]
have you installed the gogo/protobuf tooling?

try this: `go get -u github.com/gogo/protobuf/protoc-gen-gogofaster`

**Comment by modeyang** [comment]
@basvanbeek  thanks , this is work.
