### ISSUE TITLE
V0.2.2 not compatible with 1.0.0 of opentracing-go

### ISSUE THREAD

**Issue by Malayks** [openzipkin/zipkin-go-opentracing#48]
V0.2.2 of this repo is not compatible with 1.0.0 of opentracing-go because [fields](https://github.com/opentracing/opentracing-go/blob/v1.0.0/log/field.go) do not have any method named Key() and Value() which is used here https://github.com/openzipkin/zipkin-go-opentracing/blob/v0.2.2/log-materializers.go#L54. 

I get following error:
```
go/src/github.com/openzipkin/zipkin-go-opentracing/log-materializers.go:54: field.Key undefined (type "github.com/opentracing/opentracing-go/log".Field has no field or method Key, but does have "github.com/opentracing/opentracing-go/log".key)

go/src/github.com/openzipkin/zipkin-go-opentracing/log-materializers.go:54: field.Value undefined (type "vendor/github.com/opentracing/opentracing-go/log".Field has no field or method Value)
```

However master of both repos are compatible with each other. As convenience methods were added back to opentracing-go in this [PR](https://github.com/opentracing/opentracing-go/commit/2250288afc63051ce6772d513b2684630e4c9dc5)

@basvanbeek @bensigelman How about releasing a minor patch for opentracing-go since the methods are added back.

**Comment by bensigelman** [comment]
@Malayks I'm not entirely sure I understand what you're suggesting... It's pretty much impossible to get OSS Go software to guarantee behavior with non-HEAD versions of other OSS Go software since there is not yet a standard, semver-aware vendoring tool that everyone can agree on.

What exactly are you proposing we do as a fix? (I.e., what is the "minor patch" you're advocating?)

**Comment by basvanbeek** [comment]
@bensigelman I think he means releasing an opentracing-go v1.0.1 which includes the convenience methods that have been used and were added after v1.0.0. Fixing zipkin-go-opentracing so it works with v1.0.0 would be less efficient.

**Comment by bensigelman** [comment]
Ahhh, I see. Sure, happy to "release" v1.0.1. Will do.

**Comment by bensigelman** [comment]
done: https://github.com/opentracing/opentracing-go/tree/v1.0.1

**Comment by Malayks** [comment]
@bensigelman Apologies for not being clean enough. @basvanbeek got it right. I am using pinned versions of these repos and I also do not like to point to master branches. Thanks for the help.

**Comment by bensigelman** [comment]
No problem. @basvanbeek I don't have priv's to close this issue, but I believe it's resolved.

**Comment by Malayks** [comment]
@bensigelman I will close it.
