### ISSUE TITLE
Please switch to official Apache Thrift repo

### ISSUE THREAD

**Issue by bkleef** [openzipkin/zipkin-go-opentracing#54]
Currently https://github.com/apache/thrift is empty:

![](https://puu.sh/vzgaD/a02705647e.png)

Please import from `git.apache.org/thrift`.

**Comment by bkleef** [comment]
Well forget it, github.com/apache/thrift has no go meta headers.

**Comment by basvanbeek** [comment]
Let's hope this was just a very temporary issue. The github mirror has been much more reliable and quick compared to the apache hosted original. We explicitly made the change to use the github link a while ago (see #20). I'll close this issue. If you encounter the same problem again, feel free to re-open or open new issue report.

Thanks.
