### ISSUE TITLE
EVENTS ARE BEING RECORDED without the statement  span.logevent();

### ISSUE THREAD

**Issue by byeswanth** [openzipkin/zipkin-go-opentracing#56]
I have just created the span ,but not recording any events using span.logevent .Even then it is recording some events like server receive and server send .

**Comment by basvanbeek** [comment]
Can you explain what you expected?

Server Receive and Server Send and the client counterparts Client Receive and Client Send are required for spans to be handled properly by Zipkin.

**Comment by basvanbeek** [comment]
I'm going to close this one as server receive and server send annotations are to be expected when starting a span with OpenTracing SpanKindRPCServer option.
