### ISSUE TITLE
http-collector pass authorization headers

### ISSUE THREAD

**Issue by katyakirp** [openzipkin/zipkin-go-opentracing#59]
Hello, 

Could you please tell me, is there any way to add autorizhation headers in http-collector. When making requests to zipkin tool I need to send 2 headers with my request, how to add them?

**Comment by basvanbeek** [comment]
Currently there is no way, except adding your own collector (and potentially using the current http collector as example). I do see this being an important feature to support so I'm open to a PR.

Are these headers static in nature (don't change after bootstrapping the zipkin collector) or dynamic (needing the ability to alter them while collector is already running?)

**Comment by basvanbeek** [comment]
Fairly easy thing to implement... I'll have something for you shortly
