### ISSUE TITLE
Package is broken against github.com/apache/thrift/lib/go/thrift

### ISSUE THREAD

**Issue by peterbourgon** [openzipkin/zipkin-go-opentracing#68]
```
blep ~/src/github.com/go-kit/kit (master) go get -u -v github.com/openzipkin/zipkin-go-opentracing/...
 ...
 ...
 ...
github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe
# github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe
../../openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:147:28: cannot use scribeProcessorLog literal (type *scribeProcessorLog) as type thrift.TProcessorFunction in assignment:
        *scribeProcessorLog does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
../../openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:157:27: not enough arguments in call to processor.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
```

**Comment by basvanbeek** [comment]
*ugh* so they just added context (NOTE: not the stdlib one but the old x/net) to the thrift Go library but to compile a compatible thrift file the latest compiler release does not include the proper switch to enable context for generated Go code. Trying to install bleeding edge compiler in the hope it fixes the issue.

**Comment by basvanbeek** [comment]
Super... even using latest thrift Compiler it fails:

https://issues.apache.org/jira/browse/THRIFT-4260

**Comment by basvanbeek** [comment]
It compiles but is wrong. *ScribeClient should implement Scribe interface

**Comment by peterbourgon** [comment]
Is it worth reaching out to them and asking why the went with the deprecated package?

**Comment by basvanbeek** [comment]
They didn't it was my mistake. My editor opened the wrong file. They have x/context for Go versions not supporting the stdlib one.

**Comment by andriylesch** [comment]
Hello Guys, 
I have the same problem when i am trying to run 
```

**Comment by basvanbeek** [comment]
currently Thrift for Go is broken and is being worked on... once this is done I can fix on our end...

**Comment by dcelasun** [comment]
Hi everyone, a fix was just merged upstream, could you try with the latest compiler from master?

For future reference, using `master` for either the library or the compiler assumes you are using it for the other one as well. `context` support will officially be included in the upcoming 0.11 release.

**Comment by basvanbeek** [comment]
updated with PR #70...

**Comment by jayeshkhairnar** [comment]
`*metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
src/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:290: cannot use metaProcessorThriftIDL literal (type *metaProcessorThriftIDL) as type thrift.TProcessorFunction in assignment:
        *metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
src/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:291: cannot use metaProcessorVersionInfo literal (type *metaProcessorVersionInfo) as type thrift.TProcessorFunction in assignment:
        *metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
src/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:301: not enough arguments in call to processor.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
`

Above error I am getting

**Comment by basvanbeek** [comment]
@jayeshkhairnar please file your issue with github.com/uber/tchannel-go as the code they're using is not compatible anymore with master on github.com/apache/thrift/lib/go/thrift 

In the mean time you can use vendoring to provide tchannel-go with an older version / tagged release of thrift/lib/go/thrift for your application

**Comment by tpiecora** [comment]
@basvanbeek 
Getting this error when trying to build:
```vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:333:29: cannot use scribeProcessorLog literal (type *scribeProcessorLog) as type thrift.TProcessorFunction in assignment:
	*scribeProcessorLog does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:341:29: too many arguments in call to processor.Process
	have (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
	want (int32, thrift.TProtocol, thrift.TProtocol)```

I believe this is referencing the same issue: https://github.com/uber/tchannel-go/issues/648
Sounds like they have no plans for addressing this.

**Comment by basvanbeek** [comment]
@tpiecora you have an older version the thrift go library. You can fix by updating:

`go get -u github.com/apache/thrift/lib/go/thrift`

uber/tchannel-go is compatible with an older version of the thrift go library. Zipkin-go-opentracing tries to stay current with latest commits on master from its dependencies. If you desire to use older / tagged releases of these libraries you have to resort to vendoring. You can always use a tagged release from this repo.

**Comment by kingeasternsun** [comment]
cannot use agentProcessorEmitBatch literal (type *agentProcessorEmitBatch) as type thrift.TProcessorFunction in assignment:
	*agentProcessorEmitBatch does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)

**Comment by basvanbeek** [comment]
can you please update the thrift-go package, looks like you have an older one in your gopath:

`go get -u github.com/apache/thrift/lib/go/thrift`
