### ISSUE TITLE
API to wait for spans to finish sending

### ISSUE THREAD

**Issue by cstrahan** [openzipkin/zipkin-go-opentracing#74]
Would it be feasible to expose a means of waiting for the spans to finish sending? I'm experimenting with a little CLI tool I wrote, and I presently have to throw in a 1 second sleep in order for the top-most span to arrive at Zipkin.

**Comment by basvanbeek** [comment]
Please use `collector.Close()` it will block until all queued spans have been sent. See:

https://github.com/openzipkin/zipkin-go-opentracing/blob/master/examples/cli_with_2_services/cli/main.go#L88
