### ISSUE TITLE
Problem with non-string tag value

### ISSUE THREAD

**Issue by excavador** [openzipkin/zipkin-go-opentracing#77]
If I set tag by following code:
```
span.SetTag("http.status_code", 200)
```
then I can observe it in zipkin UI (as span tags), but search by query "http.status_code=200" find nothing, and I can not construct any query to find this (or similar) span.

If I set tag by following code
```
span.SetTag("http.status_code", "200")
```
then I can find it by in zipkin UI by  query "http.status_code=200"

**Comment by adriancole** [comment]
All tags should coerce to string internally so you dont have to. This
matches zipkin v2 where we drop non string support.

**Comment by excavador** [comment]
Probably we should update "SetTag" function signature - accept only strings?

**Comment by basvanbeek** [comment]
That would make us non compliant to OpenTracing's Go API. I'll be updating the serialization in the background to convert non string payloads to string before sending to the Zipkin collector.

**Comment by excavador** [comment]
Thank you! Would be great

**Comment by basvanbeek** [comment]
@excavador sorry for the late update. been away and very busy with the $$$-job.

**Comment by excavador** [comment]
@basvanbeek thank you very much!
