### ISSUE TITLE
Not existing package inside the openzipkin/zipkin-go-opentracing/propagation_ot.go

### ISSUE THREAD

**Issue by DSuhinin** [openzipkin/zipkin-go-opentracing#78]
I see this error message when I try to compile my project: ../../openzipkin/zipkin-go-opentracing/propagation_ot.go:9:2: cannot find package "github.com/gogo/protobuf/proto" in any of:
	/usr/local/Cellar/go/1.8_1/libexec/src/github.com/gogo/protobuf/proto (from $GOROOT)

and as I can see that repository github.com/gogo/protobuf/proto doesn't exists under github.

**Comment by basvanbeek** [comment]
Package does indeed exist and it is the correct source path. To see the package in your browser go here: https://github.com/gogo/protobuf/tree/master/proto

Please try the following to resolve:
`go get github.com/gogo/protobuf/proto`

**Comment by DSuhinin** [comment]
Hi, already tried this command and get next error:

There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package github.com/gogo/protobuf/proto: exit status 1

**Comment by basvanbeek** [comment]
try to remove the  `%GOPATH/src/github.com/gogo/protobuf` folder on your disk and try the go get command again. Sounds like you already have the protobuf folder but it's checked out in an inconsistent state
