### ISSUE TITLE
Fix Apache Thrift import path

### ISSUE THREAD

**Issue by julianvmodesto** [openzipkin/zipkin-go-opentracing#80]
Seems that `"github.com/apache/thrift/lib/go/thrift"` is the import path used, but `"git.apache.org/thrift.git/lib/go/thrift"` should be used instead according to this issue:

https://issues.apache.org/jira/browse/THRIFT-3131

**Comment by basvanbeek** [comment]
Thanks for the report.

Given the responsiveness, bandwidth and reliability track record of the git.apache.org repository we've deliberately chosen to switch to the github import path.

Unless we see a shift in this or we have more active users of zipkin-go-opentracing prefer the switch to git.apache.org we'll keep as is.

**Comment by julianvmodesto** [comment]
Ok that makes sense to me, appreciate your response!

**Comment by julianvmodesto** [comment]
Will close this for now
