### ISSUE TITLE
Not capable with brave librery 

### ISSUE THREAD

**Issue by skycomandor** [openzipkin/zipkin-go-opentracing#82]
brave and other zipkin libs can create id with minus and int.
Go zipkin use only uint type that means we can not use id with minus

**Comment by basvanbeek** [comment]
TraceID's in Zipkin are opaque 128 or 64 bits and SpanID's are opaque 64bits. 
There is no concept of type of integer (signed/unsigned) for these that is guaranteed to be the same for all compliant tracers. This is similar to a TraceID being able to hold the bits of a UUID but it not being of the UUID type.

Propagation of them is done in hexadecimal strings according to the B3 spec. So interop between libraries is not be an issue.

If you want to set your own ID's you can do so but if you need it to have the meaning of signed int64 you will need to do this conversion yourself. It is as simple as casting a signed int to uint64.

**Comment by adriancole** [comment]
PS in brave, we don't encourage reading the long as a number: toString, json and headers emit in hex for reasons above. Sorry if the numeric type is confusing.
