### ISSUE TITLE
api/vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:286: assignment count mismatch: 2 = 1

### ISSUE THREAD

**Issue by arthurgustin** [openzipkin/zipkin-go-opentracing#89]
Hi, got this message while updating dependancies with glide:

`api/vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:286: assignment count mismatch: 2 = 1
`

**Comment by sitano** [comment]
dupe of #86
