### ISSUE TITLE
Thrift error

### ISSUE THREAD

**Issue by sas1024** [openzipkin/zipkin-go-opentracing#91]
Hello!
I've use master branch of zipkin-go-opentracing and got this message while build my project:
`vendor/github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:210:5: undefined: thrift.TClient`

In latest apache thrift release (v0.10.0) TClient was not found.

**Comment by basvanbeek** [comment]
We're following master on the Thrift Go library (as well as all other dependencies) as we let the decision to vendor up to the package consumer. Please update your Go code in `github.com/apache/thrift/lib/go/thrift`

If you want to pin to a thrift version and still use the latest zipkin-go-opentracing lib, please regenerate the zipkin thrift code with the thrift compiler and thrift go library pinned to the version of your liking.

**Comment by mclarke47** [comment]
I feel like something like this should be documented in the README so that someone coming in blind to the library can use it without digging into issues.

**Comment by basvanbeek** [comment]
It's pretty standard for Go libraries to follow master of its dependencies and application binary projects to vendor (as final end consumer). 

Main issue here is how Thrift treats the Go code in its master and the breaking changes since this year (hasn't been a big issue before).
