### ISSUE TITLE
TraceId, SpanId, ParentSpanId encoding not complete

### ISSUE THREAD

**Issue by hullemeister** [openzipkin/zipkin-go-opentracing#97]
According to https://github.com/openzipkin/b3-propagation

TraceId is encoded as 32 or 16 lower hex characters
SpanId and ParentSpanId are encoded as 16 lower hex characters

We are running into issues because our go client f.e. sometimes sends X-B3-SpanId as 15 hexadecimal characters (when using tracer.inject) which generates an exception in tracer.Extract on the server because it expects 16 hexadecimal characters.

**Comment by basvanbeek** [comment]
yes that's a bug in the injection mechanism... about to send a PR.
